# Name of the workflow.
name: Ordered Workflow Sequence

# This workflow will run on 'push' events to any branch
# or on 'pull_request' events targeting any branch.
on:
  push:
    branches:
      - '**' # Triggers on push to any branch
  pull_request:
    branches:
      - '**' # Triggers on pull request to any branch

# Defines the jobs in this workflow.
jobs:
  # Job 1: Print Message
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print a message
        run: echo "Hello from GitHub Actions!"

  # Job 2: Ruff
  # This job will only run after 'print-message' job has successfully completed.
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Ruff linter
      uses: astral-sh/ruff-action@v3
      with:
        # Recursively lint all Python files in the repository and subdirectories
        src: "."
        # Use default ruff check command with GitHub output format
        args: "check --output-format=github ."
    - name: Run Ruff formatter check
      uses: astral-sh/ruff-action@v3
      with:
        # Recursively check formatting for all Python files in subdirectories
        src: "."
        args: "format --check --diff ."

  # Job 3: Workflows Over
  # This job will only run after 'future-placeholder' job has successfully completed.
  workflows-over:
    runs-on: ubuntu-latest
    needs: ruff
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print completion message
        run: echo "All workflows are complete!"
